version: '3'

services: 
  meuservicoweb:
    ports: 
      - "8081:8081"  
    environment:
      - IP_REDIS_FIAP=meuredis
    depends_on:
      - meuredis  
    deploy:
      replicas: 3
      mode: replicated
      restart_policy:
        condition: on-failure
  
  meuredis:
    image: redis
    ports: 
      - "6379:6379"   #expondo a porta para setar uma chave no redis.
